// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file dds_sdkTypeObjectSupport.cxx
 * Source file containing the implementation to register the TypeObject representation of the described types in the IDL file
 *
 * This file was generated by the tool fastddsgen.
 */

#include "dds_sdkTypeObjectSupport.hpp"

#include <mutex>
#include <string>

#include <fastcdr/xcdr/external.hpp>
#include <fastcdr/xcdr/optional.hpp>
#include <fastdds/dds/domain/DomainParticipantFactory.hpp>
#include <fastdds/dds/log/Log.hpp>
#include <fastdds/dds/xtypes/common.hpp>
#include <fastdds/dds/xtypes/type_representation/ITypeObjectRegistry.hpp>
#include <fastdds/dds/xtypes/type_representation/TypeObject.hpp>
#include <fastdds/dds/xtypes/type_representation/TypeObjectUtils.hpp>

#include "dds_sdk.hpp"


using namespace eprosima::fastdds::dds::xtypes;

void register_MeasurementKind_type_identifier(
        TypeIdentifierPair& type_ids_MeasurementKind)
{
    ReturnCode_t return_code_MeasurementKind {eprosima::fastdds::dds::RETCODE_OK};
    return_code_MeasurementKind =
        eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
        "MeasurementKind", type_ids_MeasurementKind);
    if (eprosima::fastdds::dds::RETCODE_OK != return_code_MeasurementKind)
    {
        AliasTypeFlag alias_flags_MeasurementKind = 0;
        QualifiedTypeName type_name_MeasurementKind = "MeasurementKind";
        eprosima::fastcdr::optional<AppliedBuiltinTypeAnnotations> type_ann_builtin_MeasurementKind;
        eprosima::fastcdr::optional<AppliedAnnotationSeq> ann_custom_MeasurementKind;
        CompleteTypeDetail detail_MeasurementKind = TypeObjectUtils::build_complete_type_detail(type_ann_builtin_MeasurementKind, ann_custom_MeasurementKind, type_name_MeasurementKind.to_string());
        CompleteAliasHeader header_MeasurementKind = TypeObjectUtils::build_complete_alias_header(detail_MeasurementKind);
        AliasMemberFlag related_flags_MeasurementKind = 0;
        return_code_MeasurementKind =
            eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
            "_uint16_t", type_ids_MeasurementKind);

        if (eprosima::fastdds::dds::RETCODE_OK != return_code_MeasurementKind)
        {
            EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                    "MeasurementKind related TypeIdentifier unknown to TypeObjectRegistry.");
            return;
        }
        bool common_MeasurementKind_ec {false};
        CommonAliasBody common_MeasurementKind {TypeObjectUtils::build_common_alias_body(related_flags_MeasurementKind,
                TypeObjectUtils::retrieve_complete_type_identifier(type_ids_MeasurementKind, common_MeasurementKind_ec))};
        if (!common_MeasurementKind_ec)
        {
            EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "MeasurementKind related TypeIdentifier inconsistent.");
            return;
        }
        eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_MeasurementKind;
        ann_custom_MeasurementKind.reset();
        CompleteAliasBody body_MeasurementKind = TypeObjectUtils::build_complete_alias_body(common_MeasurementKind,
                member_ann_builtin_MeasurementKind, ann_custom_MeasurementKind);
        CompleteAliasType alias_type_MeasurementKind = TypeObjectUtils::build_complete_alias_type(alias_flags_MeasurementKind,
                header_MeasurementKind, body_MeasurementKind);
        if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                TypeObjectUtils::build_and_register_alias_type_object(alias_type_MeasurementKind,
                    type_name_MeasurementKind.to_string(), type_ids_MeasurementKind))
        {
            EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                "MeasurementKind already registered in TypeObjectRegistry for a different type.");
        }
    }
}

// TypeIdentifier is returned by reference: dependent structures/unions are registered in this same method
void register_MValue_type_identifier(
        TypeIdentifierPair& type_ids_MValue)
{
    ReturnCode_t return_code_MValue {eprosima::fastdds::dds::RETCODE_OK};
    return_code_MValue =
        eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
        "MValue", type_ids_MValue);
    if (eprosima::fastdds::dds::RETCODE_OK != return_code_MValue)
    {
        UnionTypeFlag union_flags_MValue = TypeObjectUtils::build_union_type_flag(eprosima::fastdds::dds::xtypes::ExtensibilityKind::APPENDABLE,
                false, false);
        QualifiedTypeName type_name_MValue = "MValue";
        eprosima::fastcdr::optional<AppliedBuiltinTypeAnnotations> type_ann_builtin_MValue;
        eprosima::fastcdr::optional<AppliedAnnotationSeq> ann_custom_MValue;
        CompleteTypeDetail detail_MValue = TypeObjectUtils::build_complete_type_detail(type_ann_builtin_MValue, ann_custom_MValue, type_name_MValue.to_string());
        CompleteUnionHeader header_MValue = TypeObjectUtils::build_complete_union_header(detail_MValue);
        UnionDiscriminatorFlag member_flags_MValue = TypeObjectUtils::build_union_discriminator_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                false);
        return_code_MValue =
            eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
            "MeasurementKind", type_ids_MValue);

        if (return_code_MValue != eprosima::fastdds::dds::RETCODE_OK)
        {
::register_MeasurementKind_type_identifier(type_ids_MValue);
        }
        CommonDiscriminatorMember common_MValue;
        if (EK_COMPLETE == type_ids_MValue.type_identifier1()._d() || TK_NONE == type_ids_MValue.type_identifier2()._d())
        {
            common_MValue = TypeObjectUtils::build_common_discriminator_member(member_flags_MValue, type_ids_MValue.type_identifier1());
        }
        else if (EK_COMPLETE == type_ids_MValue.type_identifier2()._d())
        {
            common_MValue = TypeObjectUtils::build_common_discriminator_member(member_flags_MValue, type_ids_MValue.type_identifier2());
        }
        else
        {
            EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                    "MValue discriminator TypeIdentifier inconsistent.");
            return;
        }
        type_ann_builtin_MValue.reset();
        ann_custom_MValue.reset();
        CompleteDiscriminatorMember discriminator_MValue = TypeObjectUtils::build_complete_discriminator_member(common_MValue,
                type_ann_builtin_MValue, ann_custom_MValue);
        CompleteUnionMemberSeq member_seq_MValue;
        {
            return_code_MValue =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_float", type_ids_MValue);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_MValue)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "av Union member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            UnionMemberFlag member_flags_av = TypeObjectUtils::build_union_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false);
            UnionCaseLabelSeq label_seq_av;
            TypeObjectUtils::add_union_case_label(label_seq_av, static_cast<int32_t>(MK_ANALOG));
            MemberId member_id_av = 0x00000001;
            bool common_av_ec {false};
            CommonUnionMember common_av {TypeObjectUtils::build_common_union_member(member_id_av,
                    member_flags_av, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_MValue,
                        common_av_ec), label_seq_av)};
            if (!common_av_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Union av member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_av = "av";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_av;
            ann_custom_MValue.reset();
            CompleteMemberDetail detail_av = TypeObjectUtils::build_complete_member_detail(name_av, member_ann_builtin_av, ann_custom_MValue);
            CompleteUnionMember member_av = TypeObjectUtils::build_complete_union_member(common_av, detail_av);
            TypeObjectUtils::add_complete_union_member(member_seq_MValue, member_av);
        }
        {
            return_code_MValue =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_uint32_t", type_ids_MValue);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_MValue)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "dv Union member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            UnionMemberFlag member_flags_dv = TypeObjectUtils::build_union_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false);
            UnionCaseLabelSeq label_seq_dv;
            TypeObjectUtils::add_union_case_label(label_seq_dv, static_cast<int32_t>(MK_DISCRETE));
            MemberId member_id_dv = 0x00000002;
            bool common_dv_ec {false};
            CommonUnionMember common_dv {TypeObjectUtils::build_common_union_member(member_id_dv,
                    member_flags_dv, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_MValue,
                        common_dv_ec), label_seq_dv)};
            if (!common_dv_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Union dv member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_dv = "dv";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_dv;
            ann_custom_MValue.reset();
            CompleteMemberDetail detail_dv = TypeObjectUtils::build_complete_member_detail(name_dv, member_ann_builtin_dv, ann_custom_MValue);
            CompleteUnionMember member_dv = TypeObjectUtils::build_complete_union_member(common_dv, detail_dv);
            TypeObjectUtils::add_complete_union_member(member_seq_MValue, member_dv);
        }
        CompleteUnionType union_type_MValue = TypeObjectUtils::build_complete_union_type(union_flags_MValue, header_MValue, discriminator_MValue,
                member_seq_MValue);
        if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                TypeObjectUtils::build_and_register_union_type_object(union_type_MValue, type_name_MValue.to_string(), type_ids_MValue))
        {
            EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                    "MValue already registered in TypeObjectRegistry for a different type.");
        }
    }
}
// TypeIdentifier is returned by reference: dependent structures/unions are registered in this same method
void register_MeasurementValue_type_identifier(
        TypeIdentifierPair& type_ids_MeasurementValue)
{

    ReturnCode_t return_code_MeasurementValue {eprosima::fastdds::dds::RETCODE_OK};
    return_code_MeasurementValue =
        eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
        "MeasurementValue", type_ids_MeasurementValue);
    if (eprosima::fastdds::dds::RETCODE_OK != return_code_MeasurementValue)
    {
        StructTypeFlag struct_flags_MeasurementValue = TypeObjectUtils::build_struct_type_flag(eprosima::fastdds::dds::xtypes::ExtensibilityKind::APPENDABLE,
                false, false);
        QualifiedTypeName type_name_MeasurementValue = "MeasurementValue";
        eprosima::fastcdr::optional<AppliedBuiltinTypeAnnotations> type_ann_builtin_MeasurementValue;
        eprosima::fastcdr::optional<AppliedAnnotationSeq> ann_custom_MeasurementValue;
        CompleteTypeDetail detail_MeasurementValue = TypeObjectUtils::build_complete_type_detail(type_ann_builtin_MeasurementValue, ann_custom_MeasurementValue, type_name_MeasurementValue.to_string());
        CompleteStructHeader header_MeasurementValue;
        header_MeasurementValue = TypeObjectUtils::build_complete_struct_header(TypeIdentifier(), detail_MeasurementValue);
        CompleteStructMemberSeq member_seq_MeasurementValue;
        {
            TypeIdentifierPair type_ids_rid;
            ReturnCode_t return_code_rid {eprosima::fastdds::dds::RETCODE_OK};
            return_code_rid =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_uint64_t", type_ids_rid);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_rid)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "rid Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_rid = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, true, false);
            MemberId member_id_rid = 0x00000000;
            bool common_rid_ec {false};
            CommonStructMember common_rid {TypeObjectUtils::build_common_struct_member(member_id_rid, member_flags_rid, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_rid, common_rid_ec))};
            if (!common_rid_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure rid member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_rid = "rid";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_rid;
            ann_custom_MeasurementValue.reset();
            AppliedAnnotationSeq tmp_ann_custom_rid;
            eprosima::fastcdr::optional<std::string> unit_rid;
            eprosima::fastcdr::optional<AnnotationParameterValue> min_rid;
            eprosima::fastcdr::optional<AnnotationParameterValue> max_rid;
            eprosima::fastcdr::optional<std::string> hash_id_rid;
            if (unit_rid.has_value() || min_rid.has_value() || max_rid.has_value() || hash_id_rid.has_value())
            {
                member_ann_builtin_rid = TypeObjectUtils::build_applied_builtin_member_annotations(unit_rid, min_rid, max_rid, hash_id_rid);
            }
            if (!tmp_ann_custom_rid.empty())
            {
                ann_custom_MeasurementValue = tmp_ann_custom_rid;
            }
            CompleteMemberDetail detail_rid = TypeObjectUtils::build_complete_member_detail(name_rid, member_ann_builtin_rid, ann_custom_MeasurementValue);
            CompleteStructMember member_rid = TypeObjectUtils::build_complete_struct_member(common_rid, detail_rid);
            TypeObjectUtils::add_complete_struct_member(member_seq_MeasurementValue, member_rid);
        }
        {
            TypeIdentifierPair type_ids_q;
            ReturnCode_t return_code_q {eprosima::fastdds::dds::RETCODE_OK};
            return_code_q =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_uint16_t", type_ids_q);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_q)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "q Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_q = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_q = 0x00000001;
            bool common_q_ec {false};
            CommonStructMember common_q {TypeObjectUtils::build_common_struct_member(member_id_q, member_flags_q, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_q, common_q_ec))};
            if (!common_q_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure q member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_q = "q";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_q;
            ann_custom_MeasurementValue.reset();
            CompleteMemberDetail detail_q = TypeObjectUtils::build_complete_member_detail(name_q, member_ann_builtin_q, ann_custom_MeasurementValue);
            CompleteStructMember member_q = TypeObjectUtils::build_complete_struct_member(common_q, detail_q);
            TypeObjectUtils::add_complete_struct_member(member_seq_MeasurementValue, member_q);
        }
        {
            TypeIdentifierPair type_ids_v;
            ReturnCode_t return_code_v {eprosima::fastdds::dds::RETCODE_OK};
            return_code_v =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "MValue", type_ids_v);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_v)
            {
            ::register_MValue_type_identifier(type_ids_v);
            }
            StructMemberFlag member_flags_v = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_v = 0x00000002;
            bool common_v_ec {false};
            CommonStructMember common_v {TypeObjectUtils::build_common_struct_member(member_id_v, member_flags_v, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_v, common_v_ec))};
            if (!common_v_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure v member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_v = "v";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_v;
            ann_custom_MeasurementValue.reset();
            CompleteMemberDetail detail_v = TypeObjectUtils::build_complete_member_detail(name_v, member_ann_builtin_v, ann_custom_MeasurementValue);
            CompleteStructMember member_v = TypeObjectUtils::build_complete_struct_member(common_v, detail_v);
            TypeObjectUtils::add_complete_struct_member(member_seq_MeasurementValue, member_v);
        }
        CompleteStructType struct_type_MeasurementValue = TypeObjectUtils::build_complete_struct_type(struct_flags_MeasurementValue, header_MeasurementValue, member_seq_MeasurementValue);
        if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                TypeObjectUtils::build_and_register_struct_type_object(struct_type_MeasurementValue, type_name_MeasurementValue.to_string(), type_ids_MeasurementValue))
        {
            EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                    "MeasurementValue already registered in TypeObjectRegistry for a different type.");
        }
    }
}

