// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file dds_sdk.hpp
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifndef FAST_DDS_GENERATED__DDS_SDK_HPP
#define FAST_DDS_GENERATED__DDS_SDK_HPP

#include <cstdint>
#include <functional>
#include <utility>
#include <fastcdr/exceptions/BadParamException.h>


#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(DDS_SDK_SOURCE)
#define DDS_SDK_DllAPI __declspec( dllexport )
#else
#define DDS_SDK_DllAPI __declspec( dllimport )
#endif // DDS_SDK_SOURCE
#else
#define DDS_SDK_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define DDS_SDK_DllAPI
#endif // _WIN32

typedef uint16_t MeasurementKind;

const MeasurementKind MK_ANALOG = 65535;
const MeasurementKind MK_DISCRETE = 65534;
/*!
 * @brief This class represents the union MValue defined by the user in the IDL file.
 * @ingroup dds_sdk
 */
class MValue
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport MValue()
    {
    }

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~MValue()
    {
        if (member_destructor_)
        {
            member_destructor_();
        }
    }

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object MValue that will be copied.
     */
    eProsima_user_DllExport MValue(
            const MValue& x)
    {
        m__d = x.m__d;

        switch (x.selected_member_)
        {
                        case 0x00000001:
                            av_() = x.m_av;
                            break;

                        case 0x00000002:
                            dv_() = x.m_dv;
                            break;

        }
    }

    /*!
     * @brief Move constructor.
     * @param x Reference to the object MValue that will be copied.
     */
    eProsima_user_DllExport MValue(
            MValue&& x) noexcept
    {
        m__d = x.m__d;

        switch (x.selected_member_)
        {
                        case 0x00000001:
                            av_() = std::move(x.m_av);
                            break;

                        case 0x00000002:
                            dv_() = std::move(x.m_dv);
                            break;

        }
    }

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object MValue that will be copied.
     */
    eProsima_user_DllExport MValue& operator =(
            const MValue& x)
    {
        m__d = x.m__d;

        switch (x.selected_member_)
        {
                        case 0x00000001:
                            av_() = x.m_av;
                            break;

                        case 0x00000002:
                            dv_() = x.m_dv;
                            break;

        }

        return *this;
    }

    /*!
     * @brief Move assignment.
     * @param x Reference to the object MValue that will be copied.
     */
    eProsima_user_DllExport MValue& operator =(
            MValue&& x) noexcept
    {
        m__d = x.m__d;

        switch (x.selected_member_)
        {
                        case 0x00000001:
                            av_() = std::move(x.m_av);
                            break;

                        case 0x00000002:
                            dv_() = std::move(x.m_dv);
                            break;

        }

        return *this;
    }

    /*!
     * @brief Comparison operator.
     * @param x MValue object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const MValue& x) const
    {
        bool ret_value {false};

        if (m__d == x.m__d &&
                selected_member_ == x.selected_member_)
        {
            switch (selected_member_)
            {
                                case 0x00000001:
                                    ret_value = (m_av == x.m_av);
                                    break;

                                case 0x00000002:
                                    ret_value = (m_dv == x.m_dv);
                                    break;

            }
        }

        return ret_value;
    }

    /*!
     * @brief Comparison operator.
     * @param x MValue object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const MValue& x) const
    {
        return !(*this == x);
    }

    /*!
     * @brief This function sets the discriminator value.
     * @param __d New value for the discriminator.
     * @exception eprosima::fastcdr::exception::BadParamException This exception is thrown if the new value doesn't correspond to the selected union member.
     */
    eProsima_user_DllExport void _d(
            MeasurementKind __d)
    {
        bool valid_discriminator = false;

        switch (__d)
        {
                        case MK_ANALOG:
                            if (0x00000001 == selected_member_)
                            {
                                valid_discriminator = true;
                            }
                            break;

                        case MK_DISCRETE:
                            if (0x00000002 == selected_member_)
                            {
                                valid_discriminator = true;
                            }
                            break;

        }

        if (!valid_discriminator)
        {
            throw eprosima::fastcdr::exception::BadParamException("Discriminator doesn't correspond with the selected union member");
        }

        m__d = __d;
    }

    /*!
     * @brief This function returns the value of the discriminator.
     * @return Value of the discriminator
     */
    eProsima_user_DllExport MeasurementKind _d() const
    {
        return m__d;
    }

    /*!
     * @brief This function sets a value in member av
     * @param _av New value for member av
     */
    eProsima_user_DllExport void av(
            float _av)
    {
        av_() = _av;
        m__d = MK_ANALOG;
    }

    /*!
     * @brief This function returns the value of member av
     * @return Value of member av
     * @exception eprosima::fastcdr::exception::BadParamException This exception is thrown if the requested union member is not the current selection.
     */
    eProsima_user_DllExport float av() const
    {
        if (0x00000001 != selected_member_)
        {
            throw eprosima::fastcdr::exception::BadParamException("This member has not been selected");
        }

        return m_av;
    }

    /*!
     * @brief This function returns a reference to member av
     * @return Reference to member av
     * @exception eprosima::fastcdr::exception::BadParamException This exception is thrown if the requested union member is not the current selection.
     */
    eProsima_user_DllExport float& av()
    {
        if (0x00000001 != selected_member_)
        {
            throw eprosima::fastcdr::exception::BadParamException("This member has not been selected");
        }

        return m_av;
    }


    /*!
     * @brief This function sets a value in member dv
     * @param _dv New value for member dv
     */
    eProsima_user_DllExport void dv(
            uint32_t _dv)
    {
        dv_() = _dv;
        m__d = MK_DISCRETE;
    }

    /*!
     * @brief This function returns the value of member dv
     * @return Value of member dv
     * @exception eprosima::fastcdr::exception::BadParamException This exception is thrown if the requested union member is not the current selection.
     */
    eProsima_user_DllExport uint32_t dv() const
    {
        if (0x00000002 != selected_member_)
        {
            throw eprosima::fastcdr::exception::BadParamException("This member has not been selected");
        }

        return m_dv;
    }

    /*!
     * @brief This function returns a reference to member dv
     * @return Reference to member dv
     * @exception eprosima::fastcdr::exception::BadParamException This exception is thrown if the requested union member is not the current selection.
     */
    eProsima_user_DllExport uint32_t& dv()
    {
        if (0x00000002 != selected_member_)
        {
            throw eprosima::fastcdr::exception::BadParamException("This member has not been selected");
        }

        return m_dv;
    }


    void _default()
    {
        if (member_destructor_)
        {
            member_destructor_();
        }

        selected_member_ = 0x0FFFFFFFu;
    }


private:

            float& av_()
            {
                if (0x00000001 != selected_member_)
                {
                    if (member_destructor_)
                    {
                        member_destructor_();
                    }

                    selected_member_ = 0x00000001;
                    member_destructor_ = nullptr;
                    m_av = {0.0};
    ;
                }

                return m_av;
            }

            uint32_t& dv_()
            {
                if (0x00000002 != selected_member_)
                {
                    if (member_destructor_)
                    {
                        member_destructor_();
                    }

                    selected_member_ = 0x00000002;
                    member_destructor_ = nullptr;
                    m_dv = {0};
    ;
                }

                return m_dv;
            }


    MeasurementKind m__d {32767};

    union
    {
        float m_av;
        uint32_t m_dv;
    };

    uint32_t selected_member_ {0x0FFFFFFFu};

    std::function<void()> member_destructor_;
};
/*!
 * @brief This class represents the structure MeasurementValue defined by the user in the IDL file.
 * @ingroup dds_sdk
 */
class MeasurementValue
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport MeasurementValue()
    {
    }

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~MeasurementValue()
    {
    }

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object MeasurementValue that will be copied.
     */
    eProsima_user_DllExport MeasurementValue(
            const MeasurementValue& x)
    {
                    m_rid = x.m_rid;

                    m_q = x.m_q;

                    m_v = x.m_v;

    }

    /*!
     * @brief Move constructor.
     * @param x Reference to the object MeasurementValue that will be copied.
     */
    eProsima_user_DllExport MeasurementValue(
            MeasurementValue&& x) noexcept
    {
        m_rid = x.m_rid;
        m_q = x.m_q;
        m_v = std::move(x.m_v);
    }

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object MeasurementValue that will be copied.
     */
    eProsima_user_DllExport MeasurementValue& operator =(
            const MeasurementValue& x)
    {

                    m_rid = x.m_rid;

                    m_q = x.m_q;

                    m_v = x.m_v;

        return *this;
    }

    /*!
     * @brief Move assignment.
     * @param x Reference to the object MeasurementValue that will be copied.
     */
    eProsima_user_DllExport MeasurementValue& operator =(
            MeasurementValue&& x) noexcept
    {

        m_rid = x.m_rid;
        m_q = x.m_q;
        m_v = std::move(x.m_v);
        return *this;
    }

    /*!
     * @brief Comparison operator.
     * @param x MeasurementValue object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const MeasurementValue& x) const
    {
        return (m_rid == x.m_rid &&
           m_q == x.m_q &&
           m_v == x.m_v);
    }

    /*!
     * @brief Comparison operator.
     * @param x MeasurementValue object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const MeasurementValue& x) const
    {
        return !(*this == x);
    }

    /*!
     * @brief This function sets a value in member rid
     * @param _rid New value for member rid
     */
    eProsima_user_DllExport void rid(
            uint64_t _rid)
    {
        m_rid = _rid;
    }

    /*!
     * @brief This function returns the value of member rid
     * @return Value of member rid
     */
    eProsima_user_DllExport uint64_t rid() const
    {
        return m_rid;
    }

    /*!
     * @brief This function returns a reference to member rid
     * @return Reference to member rid
     */
    eProsima_user_DllExport uint64_t& rid()
    {
        return m_rid;
    }


    /*!
     * @brief This function sets a value in member q
     * @param _q New value for member q
     */
    eProsima_user_DllExport void q(
            uint16_t _q)
    {
        m_q = _q;
    }

    /*!
     * @brief This function returns the value of member q
     * @return Value of member q
     */
    eProsima_user_DllExport uint16_t q() const
    {
        return m_q;
    }

    /*!
     * @brief This function returns a reference to member q
     * @return Reference to member q
     */
    eProsima_user_DllExport uint16_t& q()
    {
        return m_q;
    }


    /*!
     * @brief This function copies the value in member v
     * @param _v New value to be copied in member v
     */
    eProsima_user_DllExport void v(
            const MValue& _v)
    {
        m_v = _v;
    }

    /*!
     * @brief This function moves the value in member v
     * @param _v New value to be moved in member v
     */
    eProsima_user_DllExport void v(
            MValue&& _v)
    {
        m_v = std::move(_v);
    }

    /*!
     * @brief This function returns a constant reference to member v
     * @return Constant reference to member v
     */
    eProsima_user_DllExport const MValue& v() const
    {
        return m_v;
    }

    /*!
     * @brief This function returns a reference to member v
     * @return Reference to member v
     */
    eProsima_user_DllExport MValue& v()
    {
        return m_v;
    }



private:

    uint64_t m_rid{0};
    uint16_t m_q{0};
    MValue m_v;

};

#endif // _FAST_DDS_GENERATED_DDS_SDK_HPP_


